### ISSUE TITLE
Increasing the size of the icons

### ISSUE THREAD

**Issue by ajtruckle** [cogdog/font-awesome-5-menus#2]
Firstly, I want to thank you for making this plugin available and I am glad i found it. I have been able to remove my previous **Menu Icons** plugin that was using 4.7 icon list. Now I am using newer icons.

You can see my **navigation menu** here:

https://www.publictalksoftware.co.uk

Previously, I think my menu icons had these additional characteristics:

- The `font-size` was `1.2em` (slightly larger than the menu text)
- The `font-weight` was `900`

Is it possible to easily bring back in that styling without breaking the system?

**Comment by cogdog** [comment]
Thanks for using the plugin. That level of styling is best done via the Custom CSS panel in your WordPress Customizer, this ought to work (I am testing via the browser inspector):

```
#primary-menu .menu-item .fas, #primary-menu .menu-item .far, #primary-menu .menu-item .fab {
    font-size: 1.2em;
    font-weight: 900;
}
```

![theo-menu](https://user-images.githubusercontent.com/463038/70548377-0be69200-1b38-11ea-81e8-70485c3da884.jpg)

**Comment by ajtruckle** [comment]
Fantastic. Works great!
