### ISSUE TITLE
Publish through WordPress plugin repository?

### ISSUE THREAD

**Issue by XenonofArcticus** [cogdog/font-awesome-5-menus#4]
The older Font Awesome plugin this is based on appears in the official WordPress plugin repository listings, but this newer one does not. This leads people to continue installing and using the older unmaintained plugin.

Could this new plugin be published so that we can direct people using the old one to adopt the new one?

https://www.godaddy.com/garage/how-to-publish-your-first-wordpress-plugin/

**Comment by cogdog** [comment]
Sure, be meaning to try this. Have never hoisted a plugin there, but am getting it ready to send.

**Comment by cogdog** [comment]
Yikes, looks like I never did this, and now it's time for version 6. Sorry. I might just take the numbering out of the name, so it can be updated.

**Comment by cogdog** [comment]
I never did sort this out, there is some issue as well using Font Awesome in the plugin name.
