### ISSUE TITLE
Download the Zip - Not Working

### ISSUE THREAD

**Issue by aboutell** [cogdog/font-awesome-5-menus#5]
Hey,

First, thanks for all the hard work you have done on all the awesome themes for WordPress, I am excited to start using them.  Next, I am attempting to download the font awesome plugin for Wordpress (from and iPad…and maybe that is the issue, idk)…however the download .zip option doesn’t exist.  I know it works on other repos, because I was able to download another repo of yours…just this one doesn’t have that option…can you help?

Thanks, Andrew

**Comment by cogdog** [comment]
It is available on the main page of this repo, as a menu option under the green **Code** button. 

Or the direct link
https://github.com/cogdog/font-awesome-5-menus/archive/refs/heads/master.zip

**Comment by aboutell** [comment]
Found it now - might have been that I was on an iPad and just didn't see it.  Thanks for the help!
